# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('image_link', models.URLField(max_length=300)),
            ],
        ),
    ]
