# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_alt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='content',
            name='use_slug',
            field=models.BooleanField(default=False),
        ),
    ]
